assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE02SHSP-SP001-09-PARADJ000
stream:
  method: telemetered
  name: parad_j_cspp_instrument
workflow_config:
  schedule: 0 0 * * *
